version: '3.9'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=kong_db
    ports:
      - 5432:5432
    networks:
      - kong-net

  kong-migrate:
    image: kong:latest
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong_db
      - KONG_PG_USER=user
      - KONG_PG_PASSWORD=12345
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-migrate
      - kong-database
    networks:
      - kong-net

  konga-prepare:
    image: pantsel/konga:latest
    command: "-c prepare -a postgres -u postgresql://user:12345@kong-database:5432/konga_db"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database

  konga:
    image: pantsel/konga:latest
    container_name: kong-ui
    restart: on-failure
    networks:
      - kong-net
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=user
      - DB_PASSWORD=12345
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      - DB_DATABASE=konga_db
      - NODE_ENV=production
      - NODE_TLS_REJECT_UNAUTHORIZED="0"
    depends_on:
      - kong-database
    ports:
      - "1337:1337"
  # catalog service
  catalog-services:
    container_name: catalog-services
    build: 
      context: ./src/LN.Catalog.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qaz@WSX
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports: 
      - "7000:80"
      - "7443:443"
    volumes:
      - ./aspnet/https:/https:ro
    networks:
      - kong-net
  logmanagement-services:
    container_name: logmanagement-services
    build: 
      context: ./src/LN.LogManagement.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=qaz@WSX
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports: 
      - "6000:80"
      - "6443:443"
    volumes:
      - ./aspnet/https:/https:ro
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge